<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><?php echo lang('label_username'); ?></th>
			<th><?php echo lang('label_full_name'); ?></th>
			<th><?php echo lang('label_crdate'); ?></th>
			<th><?php echo lang('label_enable'); ?></th>
		</tr>
	</thead>
<?php
if ($users) {
    foreach ($users as $user) {
        echo '<tr>'
            . '<td>' . $user->username . '</td>'
            . '<td>' . $user->first_name. ' ' . $user->last_name . '</td>'
            . '<td>' . mdate(DATE_FORMAT, $user->crdate) . '</td>'
            . '<td>' . ($user->crdate ? 'Yes' : 'No') . '</td>'
            . '</tr>';
    }
}
?>
</table>